name = "luna-cst0410-reader"
main = "src/workers/index.ts"
compatibility_date = "2026-09-18"
account_id = "73d83b88a2a61be02e22b16ca46d2916"

[env.production]
vars = { ENVIRONMENT = "production", LOG_LEVEL = "info", API_VERSION = "v1" }
